# -*- coding: utf-8 -*-
"""TTSDistributions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5yFVC_G8MsirtQrdB1pqX6NlM9IWu1m
"""

"""
Simulates Geometric Brownian Motion (GBM) sample paths to model exit times for investments. The simulation assumes a fixed time horizon and evaluates
when a path first hits either a +10% gain or -5% loss threshold.

For each path:
- If it hits +10%, it's recorded as a "gain"
- If it hits -5%, it's recorded as a "loss"
- Otherwise, the path is ignored

The following visualizations:
1. A scatter plot showing gain/loss outcomes by exit time
2. A bar chart showing the frequency and percentage of each outcome (-5% or +10%)
3. A histogram of exit times for all outcomes with a the middle 50%
4. Separate histograms of exit times for gain-only and loss-only outcomes

Parameters:
- T (float): Total simulation time horizon
- N (int): Number of steps per path
- S0 (float): Initial asset value
- mu (float): Drift (expected return), randomly sampled between 1% and 10%
- sigma (float): Volatility, randomly sampled between 10% and 50%
- num_paths (int): Number of GBM paths simulated

This code was used to generate visual components for a Financial Mathematics poster project on first hitting times.
"""


import numpy as np
import random as rand
import matplotlib.pyplot as plt
from scipy import stats

T = 1
N = 1000
dt = T/N
S0 = 1
upper_TTS = 1.1 * S0
lower_TTS = 0.95 * S0
num_paths = 10000
mu = rand.uniform(.01, 0.1)
sigma = rand.uniform(0.1, 0.5)

times = []
outcomes = []

def simulate_path(mu, sigma):
    X = [S0]
    for i in range(N):
        dB = np.random.normal(0, np.sqrt(dt))
        X_new = X[-1] + mu * X[-1] * dt + sigma * X[-1] * dB
        X.append(X_new)
        if X_new >= upper_TTS:
            return X, i * dt, "gain"
        elif X_new <= lower_TTS:
            return X, i * dt, "loss"
    return X, np.nan, "neutral"

for i in range(num_paths):
    path, t_hit, outcome = simulate_path(mu, sigma)
    if not np.isnan(t_hit):
        times.append(t_hit)
        outcomes.append(outcome)

times = np.array(times)
outcomes = np.array(outcomes)

plt.figure(figsize=(12,5))
gain_times = times[outcomes == "gain"]
loss_times = times[outcomes == "loss"]

plt.scatter(gain_times, np.ones_like(gain_times), color='green', alpha=0.5, label='Gain')
plt.scatter(loss_times, np.zeros_like(loss_times), color='red', alpha=0.5, label='Loss')
plt.yticks([0,1], ['Loss','Gain'])
plt.xlabel('Exit Time')
plt.title('Profit vs Time to Exit')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,5))

loss_count = np.sum(outcomes == "loss")
gain_count = np.sum(outcomes == "gain")
total = loss_count + gain_count

labels = [
    f'-5%\n{(loss_count / total) * 100:.1f}%',
    f'+10%\n{(gain_count / total) * 100:.1f}%'
]
counts = [loss_count, gain_count]
colors = ['red', 'green']

plt.bar(range(len(counts)), counts, color=colors)
plt.xticks(range(len(labels)), labels)
plt.ylabel('Frequency')
plt.title('Distribution of Profit Outcomes')
plt.grid(axis='y', linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

def plot_distribution(times_subset, title):
    plt.figure(figsize=(10,5))
    count, bins, ignored = plt.hist(times_subset, bins=50, density=True, alpha=0.6, color='gray', label='Data')
    plt.xlabel('Time to Sell')
    plt.ylabel('Probability Density')
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def plot_distribution_overall(times_subset, title):
    plt.figure(figsize=(10,5))
    plt.hist(times_subset, bins=50, density=True, alpha=0.6, color='gray', label='Data')
    q25, q75 = np.percentile(times_subset, [25, 75])
    plt.axvspan(q25, q75, color='blue', alpha=0.2, label='Middle 50%')
    plt.xlabel('Exit Time')
    plt.ylabel('Probability Density')
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

plot_distribution_overall(times, 'Distribution of Time to Sell (All Outcomes)')
plot_distribution(gain_times, 'Distribution of Time to Sell (Gains Only)')
plot_distribution(loss_times, 'Distribution of Time to Sell (Losses Only)')